#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-cells
Version  : 4.0.4
Release  : 7
URL      : https://rubygems.org/downloads/cells-4.0.4.gem
Source0  : https://rubygems.org/downloads/cells-4.0.4.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-capybara
BuildRequires : rubygem-cells-erb
BuildRequires : rubygem-minitest-reporters
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
# Cells
*View Components for Ruby and Rails.*
## Overview
Cells allow you to encapsulate parts of your UI into components into _view models_. View models, or cells, are simple ruby classes that can render templates.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n cells-4.0.4
gem spec %{SOURCE0} -l --ruby > rubygem-cells.gemspec

%build
gem build rubygem-cells.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
cells-4.0.4.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/cells-4.0.4.gem
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/CHANGES.md
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/README.md
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/TODO.md
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/cells.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/gemfiles/rails3.2.gemfile
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/gemfiles/rails4.0.gemfile
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/gemfiles/rails4.1.gemfile
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/gemfiles/rails4.2.gemfile
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/cell.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/cell/abstract.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/cell/caching.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/cell/caching/notification.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/cell/concept.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/cell/development.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/cell/escaped.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/cell/layout.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/cell/partial.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/cell/prefixes.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/cell/rails.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/cell/railtie.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/cell/self_contained.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/cell/templates.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/cell/test_case.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/cell/testing.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/cell/translation.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/cell/twin.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/cell/util.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/cell/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/cell/view_model.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/cells.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/rails/generators/cell/cell_generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/rails/generators/cell/templates/cell.rb.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/rails/generators/cell/templates/view.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/rails/generators/cell/templates/view.haml
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/rails/generators/cell/templates/view.slim
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/rails/generators/concept/concept_generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/rails/generators/concept/templates/concept.rb.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/rails/generators/concept/templates/view.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/rails/generators/concept/templates/view.haml
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/rails/generators/concept/templates/view.slim
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/rails/generators/test_unit/cell/cell_generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/rails/generators/test_unit/cell/templates/unit_test.rb.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/rails/generators/test_unit/concept/concept_generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/rails/generators/test_unit/concept/templates/unit_test.rb.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/lib/tasks/cells.rake
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/builder_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/caching_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/cell_benchmark.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/cell_generator_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/cell_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/concept_generator_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/concept_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/dummy/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/dummy/app/assets/javascripts/application.js
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/dummy/app/cells/album/assets/album.js
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/dummy/app/concepts/song/assets/songs.js
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/dummy/app/controllers/application_controller.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/dummy/app/views/layouts/application.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/dummy/app/views/musician/featured.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/dummy/app/views/musician/featured_with_block.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/dummy/app/views/musician/hamlet.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/dummy/app/views/musician/title.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/dummy/config.ru
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/dummy/config/application.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/dummy/config/boot.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/dummy/config/database.yml
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/dummy/config/environment.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/dummy/config/locales/en.yml
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/dummy/config/routes.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/dummy/script/rails
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/bassist/play.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/concepts/record/views/layout.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/concepts/record/views/show.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/concepts/record/views/song.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/inherit_views_test/popper/tap.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/inherit_views_test/tapper/play.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/inherit_views_test/tapper/tap.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/partial_test/with_partial/show.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/partials/_show.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/partials/_show.xml.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/song/ivar.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/song/show.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/song/with_erb.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/song/with_html.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/song/with_locals.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/song_with_layout/happy.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/song_with_layout/merry.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/song_with_layout/show.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/song_with_layout/show_with_layout.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/templates_caching_test/song/show.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/url_helper_test/song/edit.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/url_helper_test/song/with_block.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/url_helper_test/song/with_capture.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/url_helper_test/song/with_content_tag.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/url_helper_test/song/with_form_for_block.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/fixtures/url_helper_test/song/with_link_to.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/layout_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/partial_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/prefixes_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/property_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/public_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails/translation_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/assets/images/.keep
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/assets/stylesheets/application.css.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/cells/form_for/show.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/cells/form_for_cell.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/cells/form_tag/show.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/cells/form_tag_cell.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/cells/formtastic/show.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/cells/formtastic_cell.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/cells/simple_form/show.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/cells/simple_form_cell.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/cells/song/song.css
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/cells/song/with_escaped.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/cells/song_cell.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/controllers/application_controller.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/controllers/concerns/.keep
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/controllers/index_controller.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/controllers/songs_controller.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/helpers/application_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/mailers/.keep
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/models/.keep
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/models/artist.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/models/concerns/.keep
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/models/song.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/views/index/index.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/views/layouts/application.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/views/songs/show.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/app/views/songs/with_escaped.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/bin/bundle
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/bin/rails
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/bin/rake
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/bin/setup
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/config.ru
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/config/application.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/config/boot.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/config/environment.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/config/environments/development.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/config/environments/production.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/config/environments/test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/config/initializers/backtrace_silencers.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/config/initializers/cookies_serializer.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/config/initializers/filter_parameter_logging.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/config/initializers/formtastic.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/config/initializers/inflections.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/config/initializers/mime_types.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/config/initializers/session_store.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/config/initializers/wrap_parameters.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/config/locales/en.yml
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/config/routes.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/config/secrets.yml
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/db/seeds.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/app/assets/images/my_engine/.keep
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/app/assets/stylesheets/my_engine/application.css
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/app/concepts/user/cell.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/app/concepts/user/views/show.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/app/concepts/user/views/user.scss
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/app/controllers/my_engine/application_controller.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/app/controllers/my_engine/user_controller.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/app/helpers/my_engine/application_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/app/models/my_engine/user.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/app/views/layouts/my_engine/application.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/app/views/my_engine/user/show.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/bin/rails
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/config/routes.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/db/migrate/20150530135920_create_my_engine_users.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/lib/my_engine.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/lib/my_engine/engine.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/lib/my_engine/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/lib/tasks/my_engine_tasks.rake
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/my_engine.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/test/fixtures/my_engine/users.yml
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/engines/my_engine/test/models/my_engine/user_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/lib/assets/.keep
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/lib/tasks/.keep
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/log/.keep
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/test/integration/asset_pipeline_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/test/integration/controller_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/test/integration/form_for_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/test/integration/form_tag_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/test/integration/formtastic_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/test/integration/simple_form_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/test/integration/url_helper_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails4.2/vendor/assets/stylesheets/.keep
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/rails_extensions_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/render_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/templates_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/test_case_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.0.4/test/twin_test.rb
/usr/lib64/ruby/gems/2.3.0/specifications/cells-4.0.4.gemspec
