#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-cells
Version  : 4.1.1
Release  : 11
URL      : https://rubygems.org/downloads/cells-4.1.1.gem
Source0  : https://rubygems.org/downloads/cells-4.1.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-actionpack
BuildRequires : rubygem-activemodel
BuildRequires : rubygem-activesupport
BuildRequires : rubygem-addressable
BuildRequires : rubygem-ansi
BuildRequires : rubygem-builder
BuildRequires : rubygem-bundler
BuildRequires : rubygem-capybara
BuildRequires : rubygem-cells
BuildRequires : rubygem-cells-erb
BuildRequires : rubygem-erbse
BuildRequires : rubygem-i18n
BuildRequires : rubygem-mime-types
BuildRequires : rubygem-minitest
BuildRequires : rubygem-minitest-reporters
BuildRequires : rubygem-nokogiri
BuildRequires : rubygem-rack
BuildRequires : rubygem-rack-test
BuildRequires : rubygem-railties
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-ruby-progressbar
BuildRequires : rubygem-thor
BuildRequires : rubygem-tilt
BuildRequires : rubygem-tzinfo
BuildRequires : rubygem-uber
BuildRequires : rubygem-xpath
BuildRequires : tzdata

%description
# Cells
*View Components for Ruby and Rails.*
[![Gitter Chat](https://badges.gitter.im/trailblazer/chat.svg)](https://gitter.im/trailblazer/chat)
[![TRB Newsletter](https://img.shields.io/badge/TRB-newsletter-lightgrey.svg)](http://trailblazer.to/newsletter/)
[![Build
Status](https://travis-ci.org/apotonick/cells.svg)](https://travis-ci.org/apotonick/cells)
[![Gem Version](https://badge.fury.io/rb/cells.svg)](http://badge.fury.io/rb/cells)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n cells-4.1.1
gem spec %{SOURCE0} -l --ruby > rubygem-cells.gemspec

%build
export LANG=C
gem build rubygem-cells.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
cells-4.1.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/cells-4.1.1
ruby -v -I.:lib:test test*/test_*.rb
ruby -v -I.:lib:test test*/*_test.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/cells-4.1.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/CHANGES.md
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/README.md
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/TODO.md
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/benchmarks/class_builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/benchmarks/collection.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/cells.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/lib/cell.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/lib/cell/abstract.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/lib/cell/builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/lib/cell/caching.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/lib/cell/collection.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/lib/cell/concept.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/lib/cell/development.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/lib/cell/escaped.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/lib/cell/layout.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/lib/cell/partial.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/lib/cell/prefixes.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/lib/cell/self_contained.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/lib/cell/templates.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/lib/cell/testing.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/lib/cell/twin.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/lib/cell/util.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/lib/cell/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/lib/cell/view_model.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/lib/cells.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/lib/tasks/cells.rake
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/builder_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/cell_benchmark.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/cell_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/concept_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/context_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/bassist/play.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/cell_test/song/show_with_block.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/comment/layout/show.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/comment/show/show.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/concepts/record/views/layout.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/concepts/record/views/show.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/concepts/record/views/song.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/inherit_views_test/popper/tap.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/inherit_views_test/tapper/play.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/inherit_views_test/tapper/tap.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/partial_test/with_partial/show.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/partials/_show.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/partials/_show.xml.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/song/ivar.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/song/show.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/song/with_block.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/song/with_erb.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/song/with_html.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/song/with_locals.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/song_with_layout/happy.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/song_with_layout/merry.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/song_with_layout/show.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/song_with_layout/show_with_layout.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/templates_caching_test/song/show.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/url_helper_test/song/edit.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/url_helper_test/song/with_block.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/url_helper_test/song/with_capture.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/url_helper_test/song/with_content_tag.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/url_helper_test/song/with_form_for_block.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/fixtures/url_helper_test/song/with_link_to.erb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/layout_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/partial_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/prefixes_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/property_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/public_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/render_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/templates_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/testing_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/cells-4.1.1/test/twin_test.rb
/usr/lib64/ruby/gems/2.3.0/specifications/cells-4.1.1.gemspec
